---
- name: download collectd source
  become: yes
  become_user: root
  get_url:
    url: '{{ collectd_tgz_url }}'
    dest: /tmp/{{ collectd_tgz }}
    checksum: '{{ collectd_checksum }}'
    mode: 0644

- name: unarchive...
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: /tmp/{{ collectd_tgz }}
    dest: /opt
    creates: '{{ collectd_src_dir }}'

- name: configure...
  command: ./configure --prefix={{ collectd_target_dir }}
  args:
    chdir: '{{ collectd_src_dir }}'
    creates: /opt/{{ collectd_name }}/Makefile

- name: make all install...
  command: make all install
  args:
    chdir: '{{ collectd_src_dir }}'
    creates: '{{ collectd_target_dir }}/sbin/collectd'

- name: cleanup...
  when: collectd_build_clean
  become: yes
  become_user: root
  file:
    path: '{{ collectd_src_dir }}'
    state: absent
