---
- name: build from source...
  include: BuildFromSource.yml

- name: apply configuration...
  become: yes
  become_user: root
  with_items:
    - f: collectd.conf
      d: '{{ collectd_target_dir }}/etc'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'

- name: install collectd.service...
  register: collectd_service_updated
  become: yes
  become_user: root
  with_items:
    - f: collectd.service
      d: /etc/systemd/system
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: collectd_service_updated|changed and collectd_started
  command: systemctl daemon-reload

- name: collectd restarted/enabled
  when: collectd_started
  become: yes
  become_user: root
  service:
    name: collectd.service
    state: started
    enabled: yes
